### ISSUE TITLE
File system seems to be locked

### ISSUE THREAD

**Issue by RetiredWizard** [bill88t/ljinux#52] opened 2022-07-28 23:36 UTC
I don't know if it has something to do with my build on an esp32-s2 but when I try to create a file with say `cp Manual.txt x.x` the following error is displayed:

     Traceback (most recent call last):
             OSError:

**Comment by bill88t** [comment] 2022-07-29 08:53
Is the board in development mode?

**Comment by RetiredWizard** [comment] 2022-07-29 14:59
Not intentionally, I really haven't played with much other than getting the install script working. All I do is run the install, power cycle the board and connect to the ljinux console at which point I don't seem to be able to write to the file system.

**Comment by bill88t** [comment] 2022-08-04 20:58
Fixed with 3b93e706652de9abd04fd04a4bbd149741ace0db. The `cp` command was broken, that's all.
Sorry for the delay.

Ljinux devmode enables usb file access, that's all. If you can't see the board from your file manager it's disabled.
To enable it just run `devmode` from within ljinux.
The issue is, that as long as it's active, ljinux can't write to the filesystem.
So commands like cp, nano, mkdir won't work.

**Closed by bill88t** 2022-08-04 20:58 UTC
