### ISSUE TITLE
incorrect led colors on RP2040-Zero

### ISSUE THREAD

**Issue by vrz** [bill88t/ljinux#77] opened 2023-02-22 15:41 UTC
for correct led colors(as in Manual.txt) file neopixel_colors.py have to be changed:
line  6:      idle = bytearray([0, 3, 0])  # for idling in terminal
line  7:      idletype = bytearray([0, 2, 0])  # alternative idle, to indicate input

line 14:      error = bytearray([50, 0, 0])  # when errors occur

**Comment by bill88t** [comment] 2023-02-22 15:58
Hmm. The neopixel colors are precisely how I intended them to be.
If the manual is out of date, that is another thing.

**Comment by vrz** [comment] 2023-02-22 16:15
it's possible that used different led chips and they have different colors order

**Comment by bill88t** [comment] 2023-02-27 18:47
I verified the colors, they are as intended. Sample size of three `waveshare_rp2040_zero`'s, `circuitpython 8.0.3`.
Even if different led chips were used, color-matching them to one specific led type is not gonna happen, since the same color codes are also being used for regular tri-color leds (which will look way different).

Closing this issue for now.

**Closed by bill88t** 2023-02-27 18:47 UTC
